name: toaster_linear
description: A rudimentary Linear Algebra Library.
version: 1.0.0
homepage: https://edtoaster.github.io
author: EDToaster 

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.0.0
